#debug:
#  true
spring:
  profiles:
    active: dev

logging:
  pattern:
    console: "%d -- %msg%n"

configs:
  # 过期时间（分钟）
  timeOut: 30
  # 某个群体没评价时，预估好评率
  proportion: 0.8
  # 留言每次显示条数
  msgPageSize: 10